from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from ControlInputType import ControlInputType
from ControlMode import ControlMode

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Control(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Control: ...
  @classmethod
  def GetRootAsControl(cls, buf: bytes, offset: int) -> Control: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def File(self) -> str | None: ...
  def Weight(self) -> float: ...
  def GuidanceStart(self) -> float: ...
  def GuidanceEnd(self) -> float: ...
  def NoPrompt(self) -> bool: ...
  def GlobalAveragePooling(self) -> bool: ...
  def DownSamplingRate(self) -> float: ...
  def ControlMode(self) -> typing.Literal[ControlMode.Balanced, ControlMode.Prompt, ControlMode.Control]: ...
  def TargetBlocks(self, i: int) -> str: ...
  def TargetBlocksLength(self) -> int: ...
  def TargetBlocksIsNone(self) -> bool: ...
  def InputOverride(self) -> typing.Literal[ControlInputType.Unspecified, ControlInputType.Custom, ControlInputType.Depth, ControlInputType.Canny, ControlInputType.Scribble, ControlInputType.Pose, ControlInputType.Normalbae, ControlInputType.Color, ControlInputType.Lineart, ControlInputType.Softedge, ControlInputType.Seg, ControlInputType.Inpaint, ControlInputType.Ip2p, ControlInputType.Shuffle, ControlInputType.Mlsd, ControlInputType.Tile, ControlInputType.Blur, ControlInputType.Lowquality, ControlInputType.Gray]: ...
def ControlStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def ControlAddFile(builder: flatbuffers.Builder, file: uoffset) -> None: ...
def ControlAddWeight(builder: flatbuffers.Builder, weight: float) -> None: ...
def ControlAddGuidanceStart(builder: flatbuffers.Builder, guidanceStart: float) -> None: ...
def ControlAddGuidanceEnd(builder: flatbuffers.Builder, guidanceEnd: float) -> None: ...
def ControlAddNoPrompt(builder: flatbuffers.Builder, noPrompt: bool) -> None: ...
def ControlAddGlobalAveragePooling(builder: flatbuffers.Builder, globalAveragePooling: bool) -> None: ...
def ControlAddDownSamplingRate(builder: flatbuffers.Builder, downSamplingRate: float) -> None: ...
def ControlAddControlMode(builder: flatbuffers.Builder, controlMode: typing.Literal[ControlMode.Balanced, ControlMode.Prompt, ControlMode.Control]) -> None: ...
def ControlAddTargetBlocks(builder: flatbuffers.Builder, targetBlocks: uoffset) -> None: ...
def ControlStartTargetBlocksVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartTargetBlocksVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def ControlAddInputOverride(builder: flatbuffers.Builder, inputOverride: typing.Literal[ControlInputType.Unspecified, ControlInputType.Custom, ControlInputType.Depth, ControlInputType.Canny, ControlInputType.Scribble, ControlInputType.Pose, ControlInputType.Normalbae, ControlInputType.Color, ControlInputType.Lineart, ControlInputType.Softedge, ControlInputType.Seg, ControlInputType.Inpaint, ControlInputType.Ip2p, ControlInputType.Shuffle, ControlInputType.Mlsd, ControlInputType.Tile, ControlInputType.Blur, ControlInputType.Lowquality, ControlInputType.Gray]) -> None: ...
def ControlEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

