from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from Control import Control
from LoRA import LoRA
from SamplerType import SamplerType
from SeedMode import SeedMode

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class GenerationConfiguration(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> GenerationConfiguration: ...
  @classmethod
  def GetRootAsGenerationConfiguration(cls, buf: bytes, offset: int) -> GenerationConfiguration: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> int: ...
  def StartWidth(self) -> int: ...
  def StartHeight(self) -> int: ...
  def Seed(self) -> int: ...
  def Steps(self) -> int: ...
  def GuidanceScale(self) -> float: ...
  def Strength(self) -> float: ...
  def Model(self) -> str | None: ...
  def Sampler(self) -> typing.Literal[SamplerType.DPMPP2MKarras, SamplerType.EulerA, SamplerType.DDIM, SamplerType.PLMS, SamplerType.DPMPPSDEKarras, SamplerType.UniPC, SamplerType.LCM, SamplerType.EulerASubstep, SamplerType.DPMPPSDESubstep, SamplerType.TCD, SamplerType.EulerATrailing, SamplerType.DPMPPSDETrailing, SamplerType.DPMPP2MAYS, SamplerType.EulerAAYS, SamplerType.DPMPPSDEAYS, SamplerType.DPMPP2MTrailing, SamplerType.DDIMTrailing]: ...
  def BatchCount(self) -> int: ...
  def BatchSize(self) -> int: ...
  def HiresFix(self) -> bool: ...
  def HiresFixStartWidth(self) -> int: ...
  def HiresFixStartHeight(self) -> int: ...
  def HiresFixStrength(self) -> float: ...
  def Upscaler(self) -> str | None: ...
  def ImageGuidanceScale(self) -> float: ...
  def SeedMode(self) -> typing.Literal[SeedMode.Legacy, SeedMode.TorchCpuCompatible, SeedMode.ScaleAlike, SeedMode.NvidiaGpuCompatible]: ...
  def ClipSkip(self) -> int: ...
  def Controls(self, i: int) -> Control | None: ...
  def ControlsLength(self) -> int: ...
  def ControlsIsNone(self) -> bool: ...
  def Loras(self, i: int) -> LoRA | None: ...
  def LorasLength(self) -> int: ...
  def LorasIsNone(self) -> bool: ...
  def MaskBlur(self) -> float: ...
  def FaceRestoration(self) -> str | None: ...
  def ClipWeight(self) -> float: ...
  def NegativePromptForImagePrior(self) -> bool: ...
  def ImagePriorSteps(self) -> int: ...
  def RefinerModel(self) -> str | None: ...
  def OriginalImageHeight(self) -> int: ...
  def OriginalImageWidth(self) -> int: ...
  def CropTop(self) -> int: ...
  def CropLeft(self) -> int: ...
  def TargetImageHeight(self) -> int: ...
  def TargetImageWidth(self) -> int: ...
  def AestheticScore(self) -> float: ...
  def NegativeAestheticScore(self) -> float: ...
  def ZeroNegativePrompt(self) -> bool: ...
  def RefinerStart(self) -> float: ...
  def NegativeOriginalImageHeight(self) -> int: ...
  def NegativeOriginalImageWidth(self) -> int: ...
  def Name(self) -> str | None: ...
  def FpsId(self) -> int: ...
  def MotionBucketId(self) -> int: ...
  def CondAug(self) -> float: ...
  def StartFrameCfg(self) -> float: ...
  def NumFrames(self) -> int: ...
  def MaskBlurOutset(self) -> int: ...
  def Sharpness(self) -> float: ...
  def Shift(self) -> float: ...
  def Stage2Steps(self) -> int: ...
  def Stage2Cfg(self) -> float: ...
  def Stage2Shift(self) -> float: ...
  def TiledDecoding(self) -> bool: ...
  def DecodingTileWidth(self) -> int: ...
  def DecodingTileHeight(self) -> int: ...
  def DecodingTileOverlap(self) -> int: ...
  def StochasticSamplingGamma(self) -> float: ...
  def PreserveOriginalAfterInpaint(self) -> bool: ...
  def TiledDiffusion(self) -> bool: ...
  def DiffusionTileWidth(self) -> int: ...
  def DiffusionTileHeight(self) -> int: ...
  def DiffusionTileOverlap(self) -> int: ...
  def UpscalerScaleFactor(self) -> int: ...
  def T5TextEncoder(self) -> bool: ...
  def SeparateClipL(self) -> bool: ...
  def ClipLText(self) -> str | None: ...
  def SeparateOpenClipG(self) -> bool: ...
  def OpenClipGText(self) -> str | None: ...
  def SpeedUpWithGuidanceEmbed(self) -> bool: ...
  def GuidanceEmbed(self) -> float: ...
  def ResolutionDependentShift(self) -> bool: ...
  def TeaCacheStart(self) -> int: ...
  def TeaCacheEnd(self) -> int: ...
  def TeaCacheThreshold(self) -> float: ...
  def TeaCache(self) -> bool: ...
def GenerationConfigurationStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def GenerationConfigurationAddId(builder: flatbuffers.Builder, id: int) -> None: ...
def GenerationConfigurationAddStartWidth(builder: flatbuffers.Builder, startWidth: int) -> None: ...
def GenerationConfigurationAddStartHeight(builder: flatbuffers.Builder, startHeight: int) -> None: ...
def GenerationConfigurationAddSeed(builder: flatbuffers.Builder, seed: int) -> None: ...
def GenerationConfigurationAddSteps(builder: flatbuffers.Builder, steps: int) -> None: ...
def GenerationConfigurationAddGuidanceScale(builder: flatbuffers.Builder, guidanceScale: float) -> None: ...
def GenerationConfigurationAddStrength(builder: flatbuffers.Builder, strength: float) -> None: ...
def GenerationConfigurationAddModel(builder: flatbuffers.Builder, model: uoffset) -> None: ...
def GenerationConfigurationAddSampler(builder: flatbuffers.Builder, sampler: typing.Literal[SamplerType.DPMPP2MKarras, SamplerType.EulerA, SamplerType.DDIM, SamplerType.PLMS, SamplerType.DPMPPSDEKarras, SamplerType.UniPC, SamplerType.LCM, SamplerType.EulerASubstep, SamplerType.DPMPPSDESubstep, SamplerType.TCD, SamplerType.EulerATrailing, SamplerType.DPMPPSDETrailing, SamplerType.DPMPP2MAYS, SamplerType.EulerAAYS, SamplerType.DPMPPSDEAYS, SamplerType.DPMPP2MTrailing, SamplerType.DDIMTrailing]) -> None: ...
def GenerationConfigurationAddBatchCount(builder: flatbuffers.Builder, batchCount: int) -> None: ...
def GenerationConfigurationAddBatchSize(builder: flatbuffers.Builder, batchSize: int) -> None: ...
def GenerationConfigurationAddHiresFix(builder: flatbuffers.Builder, hiresFix: bool) -> None: ...
def GenerationConfigurationAddHiresFixStartWidth(builder: flatbuffers.Builder, hiresFixStartWidth: int) -> None: ...
def GenerationConfigurationAddHiresFixStartHeight(builder: flatbuffers.Builder, hiresFixStartHeight: int) -> None: ...
def GenerationConfigurationAddHiresFixStrength(builder: flatbuffers.Builder, hiresFixStrength: float) -> None: ...
def GenerationConfigurationAddUpscaler(builder: flatbuffers.Builder, upscaler: uoffset) -> None: ...
def GenerationConfigurationAddImageGuidanceScale(builder: flatbuffers.Builder, imageGuidanceScale: float) -> None: ...
def GenerationConfigurationAddSeedMode(builder: flatbuffers.Builder, seedMode: typing.Literal[SeedMode.Legacy, SeedMode.TorchCpuCompatible, SeedMode.ScaleAlike, SeedMode.NvidiaGpuCompatible]) -> None: ...
def GenerationConfigurationAddClipSkip(builder: flatbuffers.Builder, clipSkip: int) -> None: ...
def GenerationConfigurationAddControls(builder: flatbuffers.Builder, controls: uoffset) -> None: ...
def GenerationConfigurationStartControlsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartControlsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def GenerationConfigurationAddLoras(builder: flatbuffers.Builder, loras: uoffset) -> None: ...
def GenerationConfigurationStartLorasVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartLorasVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def GenerationConfigurationAddMaskBlur(builder: flatbuffers.Builder, maskBlur: float) -> None: ...
def GenerationConfigurationAddFaceRestoration(builder: flatbuffers.Builder, faceRestoration: uoffset) -> None: ...
def GenerationConfigurationAddClipWeight(builder: flatbuffers.Builder, clipWeight: float) -> None: ...
def GenerationConfigurationAddNegativePromptForImagePrior(builder: flatbuffers.Builder, negativePromptForImagePrior: bool) -> None: ...
def GenerationConfigurationAddImagePriorSteps(builder: flatbuffers.Builder, imagePriorSteps: int) -> None: ...
def GenerationConfigurationAddRefinerModel(builder: flatbuffers.Builder, refinerModel: uoffset) -> None: ...
def GenerationConfigurationAddOriginalImageHeight(builder: flatbuffers.Builder, originalImageHeight: int) -> None: ...
def GenerationConfigurationAddOriginalImageWidth(builder: flatbuffers.Builder, originalImageWidth: int) -> None: ...
def GenerationConfigurationAddCropTop(builder: flatbuffers.Builder, cropTop: int) -> None: ...
def GenerationConfigurationAddCropLeft(builder: flatbuffers.Builder, cropLeft: int) -> None: ...
def GenerationConfigurationAddTargetImageHeight(builder: flatbuffers.Builder, targetImageHeight: int) -> None: ...
def GenerationConfigurationAddTargetImageWidth(builder: flatbuffers.Builder, targetImageWidth: int) -> None: ...
def GenerationConfigurationAddAestheticScore(builder: flatbuffers.Builder, aestheticScore: float) -> None: ...
def GenerationConfigurationAddNegativeAestheticScore(builder: flatbuffers.Builder, negativeAestheticScore: float) -> None: ...
def GenerationConfigurationAddZeroNegativePrompt(builder: flatbuffers.Builder, zeroNegativePrompt: bool) -> None: ...
def GenerationConfigurationAddRefinerStart(builder: flatbuffers.Builder, refinerStart: float) -> None: ...
def GenerationConfigurationAddNegativeOriginalImageHeight(builder: flatbuffers.Builder, negativeOriginalImageHeight: int) -> None: ...
def GenerationConfigurationAddNegativeOriginalImageWidth(builder: flatbuffers.Builder, negativeOriginalImageWidth: int) -> None: ...
def GenerationConfigurationAddName(builder: flatbuffers.Builder, name: uoffset) -> None: ...
def GenerationConfigurationAddFpsId(builder: flatbuffers.Builder, fpsId: int) -> None: ...
def GenerationConfigurationAddMotionBucketId(builder: flatbuffers.Builder, motionBucketId: int) -> None: ...
def GenerationConfigurationAddCondAug(builder: flatbuffers.Builder, condAug: float) -> None: ...
def GenerationConfigurationAddStartFrameCfg(builder: flatbuffers.Builder, startFrameCfg: float) -> None: ...
def GenerationConfigurationAddNumFrames(builder: flatbuffers.Builder, numFrames: int) -> None: ...
def GenerationConfigurationAddMaskBlurOutset(builder: flatbuffers.Builder, maskBlurOutset: int) -> None: ...
def GenerationConfigurationAddSharpness(builder: flatbuffers.Builder, sharpness: float) -> None: ...
def GenerationConfigurationAddShift(builder: flatbuffers.Builder, shift: float) -> None: ...
def GenerationConfigurationAddStage2Steps(builder: flatbuffers.Builder, stage2Steps: int) -> None: ...
def GenerationConfigurationAddStage2Cfg(builder: flatbuffers.Builder, stage2Cfg: float) -> None: ...
def GenerationConfigurationAddStage2Shift(builder: flatbuffers.Builder, stage2Shift: float) -> None: ...
def GenerationConfigurationAddTiledDecoding(builder: flatbuffers.Builder, tiledDecoding: bool) -> None: ...
def GenerationConfigurationAddDecodingTileWidth(builder: flatbuffers.Builder, decodingTileWidth: int) -> None: ...
def GenerationConfigurationAddDecodingTileHeight(builder: flatbuffers.Builder, decodingTileHeight: int) -> None: ...
def GenerationConfigurationAddDecodingTileOverlap(builder: flatbuffers.Builder, decodingTileOverlap: int) -> None: ...
def GenerationConfigurationAddStochasticSamplingGamma(builder: flatbuffers.Builder, stochasticSamplingGamma: float) -> None: ...
def GenerationConfigurationAddPreserveOriginalAfterInpaint(builder: flatbuffers.Builder, preserveOriginalAfterInpaint: bool) -> None: ...
def GenerationConfigurationAddTiledDiffusion(builder: flatbuffers.Builder, tiledDiffusion: bool) -> None: ...
def GenerationConfigurationAddDiffusionTileWidth(builder: flatbuffers.Builder, diffusionTileWidth: int) -> None: ...
def GenerationConfigurationAddDiffusionTileHeight(builder: flatbuffers.Builder, diffusionTileHeight: int) -> None: ...
def GenerationConfigurationAddDiffusionTileOverlap(builder: flatbuffers.Builder, diffusionTileOverlap: int) -> None: ...
def GenerationConfigurationAddUpscalerScaleFactor(builder: flatbuffers.Builder, upscalerScaleFactor: int) -> None: ...
def GenerationConfigurationAddT5TextEncoder(builder: flatbuffers.Builder, t5TextEncoder: bool) -> None: ...
def GenerationConfigurationAddSeparateClipL(builder: flatbuffers.Builder, separateClipL: bool) -> None: ...
def GenerationConfigurationAddClipLText(builder: flatbuffers.Builder, clipLText: uoffset) -> None: ...
def GenerationConfigurationAddSeparateOpenClipG(builder: flatbuffers.Builder, separateOpenClipG: bool) -> None: ...
def GenerationConfigurationAddOpenClipGText(builder: flatbuffers.Builder, openClipGText: uoffset) -> None: ...
def GenerationConfigurationAddSpeedUpWithGuidanceEmbed(builder: flatbuffers.Builder, speedUpWithGuidanceEmbed: bool) -> None: ...
def GenerationConfigurationAddGuidanceEmbed(builder: flatbuffers.Builder, guidanceEmbed: float) -> None: ...
def GenerationConfigurationAddResolutionDependentShift(builder: flatbuffers.Builder, resolutionDependentShift: bool) -> None: ...
def GenerationConfigurationAddTeaCacheStart(builder: flatbuffers.Builder, teaCacheStart: int) -> None: ...
def GenerationConfigurationAddTeaCacheEnd(builder: flatbuffers.Builder, teaCacheEnd: int) -> None: ...
def GenerationConfigurationAddTeaCacheThreshold(builder: flatbuffers.Builder, teaCacheThreshold: float) -> None: ...
def GenerationConfigurationAddTeaCache(builder: flatbuffers.Builder, teaCache: bool) -> None: ...
def GenerationConfigurationEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

