from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class LoRA(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> LoRA: ...
  @classmethod
  def GetRootAsLoRA(cls, buf: bytes, offset: int) -> LoRA: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def File(self) -> str | None: ...
  def Weight(self) -> float: ...
def LoRAStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def LoRAAddFile(builder: flatbuffers.Builder, file: uoffset) -> None: ...
def LoRAAddWeight(builder: flatbuffers.Builder, weight: float) -> None: ...
def LoRAEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

